nome = input('Nome do Filme: ')
qualidade = input('Qualidade do Filme: ')
link = input('Link do Filme: ')
thumbmail = input('Thumbmail do Filme: ')
trailer = input('Trailer do Filme: ')
sinopse = input('sinopse do Filme: ')


print("<channels></channels>")
print("<channel>")
print("<name>"+nome+"</name>")
print("<thumbnail>"+thumbmail+"</thumbnail>")
print("\n")
print("<item>")
print("<title>"+nome+" - "+qualidade+"</title>")
print("<link>"+link+"</link>")
print("<thumbnail>"+thumbmail+"</thumbnail>")
print("<fanart></fanart>")
print("<info>"+sinopse+"</info>")
print("</item>")
print("\n")
print("<item>")
print("<title>Trailer</title>")
print("<trailer>plugin://plugin.video.youtube/?action=play_video&amp;videoid="+trailer+"</trailer>")
print("<thumbnail>"+thumbmail+"</thumbnail>")
print("<fanart></fanart>")
print("<info>"+sinopse+"</info>")
print("</item>")
print("</channel>")
